shopping_list=["Watch","Laptop","Shoes","Pen","Clothes"]
shopping_list.append("Football")
print(shopping_list[0])
print(shopping_list[-1])
print(shopping_list)
print(shopping_list[1:3])
shopping_list[3]="Notebook"
del(shopping_list[4])
print(shopping_list)
